replicaCount: 2

httpRoute:
  enabled: false

image:
  repository: ashokit/maven-web-app
  tag: latest
  pullPolicy: Always

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
  # targetMemoryUtilizationPercentage: 70

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 100m        # 0.1 core (required for HPA)
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
