apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mavenwebapp.fullname" . }}
  labels:
    app: {{ include "mavenwebapp.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "mavenwebapp.name" . }}
  template:
    metadata:
      name: {{ include "mavenwebapp.name" . }}-pod
      labels:
        app: {{ include "mavenwebapp.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}

